INSERT INTO BOARD(TITLE, CONTENTS, WRITER)
VALUES('나 의천인데 나만 다들 바라봤으면 좋겠다', '내가 주인공이니까', '조의천');
INSERT INTO BOARD(TITLE, CONTENTS, WRITER)
VALUES('안녕 나는 엘사라고 해', '렛잇고~ 렛잇고~', '엘사');
INSERT INTO BOARD(TITLE, CONTENTS, WRITER)
VALUES('HELLO', 'HE HE', 'HELLLLL');

COMMIT;

SELECT * FROM BOARD;